<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Testng Automation Suite" duration-ms="167987" started-at="2019-01-07T15:48:43Z" finished-at="2019-01-07T15:51:31Z">
    <groups>
    </groups>
    <test name="Regression suite 1" duration-ms="167987" started-at="2019-01-07T15:48:43Z" finished-at="2019-01-07T15:51:31Z">
      <class name="Deployment.Testcases.WomenTest">
        <test-method status="PASS" signature="validate_women()[pri:0, instance:Deployment.Testcases.WomenTest@5e5792a0]" name="validate_women" duration-ms="57350" started-at="2019-01-07T15:48:43Z" finished-at="2019-01-07T15:49:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_women -->
      </class> <!-- Deployment.Testcases.WomenTest -->
      <class name="Deployment.Testcases.MenTest">
        <test-method status="PASS" signature="validate_men()[pri:1, instance:Deployment.Testcases.MenTest@26653222]" name="validate_men" duration-ms="54450" started-at="2019-01-07T15:49:41Z" finished-at="2019-01-07T15:50:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validate_men -->
      </class> <!-- Deployment.Testcases.MenTest -->
      <class name="Deployment.Testcases.SignUpErrorHandling">
        <test-method status="PASS" signature="InvalidEmail()[pri:2, instance:Deployment.Testcases.SignUpErrorHandling@3532ec19]" name="InvalidEmail" duration-ms="23438" started-at="2019-01-07T15:50:35Z" finished-at="2019-01-07T15:50:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidEmail -->
        <test-method status="PASS" signature="PasswordNotMatch()[pri:3, instance:Deployment.Testcases.SignUpErrorHandling@3532ec19]" name="PasswordNotMatch" duration-ms="21974" started-at="2019-01-07T15:50:59Z" finished-at="2019-01-07T15:51:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PasswordNotMatch -->
      </class> <!-- Deployment.Testcases.SignUpErrorHandling -->
      <class name="Deployment.Testcases.Verify_Login">
        <test-method status="FAIL" signature="checkValidCredentials()[pri:4, instance:Deployment.Testcases.Verify_Login@68c4039c]" name="checkValidCredentials" duration-ms="10712" started-at="2019-01-07T15:51:21Z" finished-at="2019-01-07T15:51:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at com.sun.proxy.$Proxy7.isDisplayed(Unknown Source)
at org.openqa.selenium.support.ui.ExpectedConditions.elementIfVisible(ExpectedConditions.java:315)
at org.openqa.selenium.support.ui.ExpectedConditions.access$100(ExpectedConditions.java:44)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:301)
at org.openqa.selenium.support.ui.ExpectedConditions$10.apply(ExpectedConditions.java:298)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
at Utility.Synchronization.sendKeys(Synchronization.java:47)
at com.pages.Login.login_selfie_styler(Login.java:55)
at Deployment.Testcases.Verify_Login.checkValidCredentials(Verify_Login.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkValidCredentials -->
      </class> <!-- Deployment.Testcases.Verify_Login -->
    </test> <!-- Regression suite 1 -->
  </suite> <!-- Testng Automation Suite -->
</testng-results>
