<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16312" started-at="2019-01-25T16:30:52Z" finished-at="2019-01-25T16:31:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16312" started-at="2019-01-25T16:30:52Z" finished-at="2019-01-25T16:31:08Z">
      <class name="Console.Error.Blog_console">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:Console.Error.Blog_console@e25b2fe]" name="setExtent" is-config="true" duration-ms="153" started-at="2019-01-25T16:30:52Z" finished-at="2019-01-25T16:30:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="setup()[pri:0, instance:Console.Error.Blog_console@e25b2fe]" name="setup" is-config="true" duration-ms="9792" started-at="2019-01-25T16:30:52Z" finished-at="2019-01-25T16:31:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Blog_Console_Error()[pri:5, instance:Console.Error.Blog_console@e25b2fe]" name="Blog_Console_Error" duration-ms="4907" started-at="2019-01-25T16:31:02Z" finished-at="2019-01-25T16:31:07Z">
          <exception class="org.apache.commons.mail.EmailException">
            <message>
              <![CDATA[Invalid message supplied]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.commons.mail.EmailException: Invalid message supplied
at org.apache.commons.mail.SimpleEmail.setMsg(SimpleEmail.java:48)
at Console.Error.Blog_console.extractJSLogsInfo(Blog_console.java:72)
at Console.Error.Blog_console.Blog_Console_Error(Blog_console.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.commons.mail.EmailException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Blog_Console_Error -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Console.Error.Blog_console@e25b2fe]" name="tearDown" is-config="true" duration-ms="1129" started-at="2019-01-25T16:31:07Z" finished-at="2019-01-25T16:31:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Blog_Console_Error status=FAILURE method=Blog_console.Blog_Console_Error()[pri:5, instance:Console.Error.Blog_console@e25b2fe] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:Console.Error.Blog_console@e25b2fe]" name="endReport" is-config="true" duration-ms="308" started-at="2019-01-25T16:31:08Z" finished-at="2019-01-25T16:31:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- Console.Error.Blog_console -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
